[package]
name = "datastar-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
futures-util = "0.3.31"
maud = { version = "0.27.0", features = ["axum"] }
tokio = { version = "1.49.0", features = ["rt-multi-thread"] }
